### ISSUE TITLE
Semantic release workflow fails if publishing a public package

### ISSUE THREAD

**Issue by codetheweb** [seamapi/seam-plop#33]
When a semantic release workflow is generated for a public package (not `@seamapi/*`) the workflow includes:

```yaml
...
- name: Setup Node.js
  uses: actions/setup-node@v2
  with:
    node-version: "16.x"
    registry-url: "https://registry.npmjs.org"
    cache: "yarn"
...
```

This fails because the registry URL cannot be specified as it causes semantic release to not create a `.npmrc` with the correct token. Instead, this step needs to look like

```yaml
- name: Setup Node.js
  uses: actions/setup-node@v2
  with:
    node-version: "16.x"
    cache: "yarn"
```
